name: 'Polaris Action'
description: 'Initiate SAST scans based on code changes and pushs scan results for display in GitHub.'
author: 'DevSecOps Team @ Synopsys SIG'
branding:
  icon: 'shield'
  color: 'purple'
inputs:
  polarisServerUrl:
    description: 'The server Host URL for Polaris tool eg https://abc.polaris.synopsys.com'
    required: true
  polarisAccessToken:
    description: 'The server access token for Polaris tool'
    required: true
  polarisProjectName:
    description: 'The name of the Polaris project'
    required: true
  polarisAdditionalArgs:
    description: 'Additional arguments for Polaris tool'
    required: false
    default: ""
  githubUrl:
    description: 'Github URL for Polaris Incremental Scan'
    required: false
    default: ""
  githubCreds:
    description: 'Github Credentials for Polaris Incremental Scan'
    required: false
    default: ""
    
runs:
  using: 'node12'
  main: 'index.js'
